name: Full Stack CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: |
          frontend/package-lock.json
          backend/package-lock.json

    - name: Install Frontend Dependencies
      working-directory: frontend
      run: npm ci

    - name: Build Frontend
      working-directory: frontend
      run: npm run build

    - name: Run Frontend Tests (if any)
      working-directory: frontend
      run: npm test

    - name: Install Backend Dependencies
      working-directory: backend
      run: npm ci

    - name: Run Backend Tests (if any)
      working-directory: backend
      run: npm test
