name: Full Stack CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: |
          frontend/package-lock.json
          backend/package-lock.json

    # FRONTEND
    - name: Install Frontend Dependencies
      working-directory: frontend
      run: npm ci

    - name: Lint Frontend Code
      working-directory: frontend
      run: |
        # Uncomment this if you use eslint
        # npm run lint

    - name: Type Check Frontend
      working-directory: frontend
      run: |
        # Uncomment this if you use TypeScript
        # npm run type-check

    - name: Build Frontend
      working-directory: frontend
      run: npm run build

    - name: Run Frontend Tests
      working-directory: frontend
      run: |
        # Optional: include only if you have test setup
        npm test

    # BACKEND
    - name: Install Backend Dependencies
      working-directory: backend
      run: npm ci

    - name: Lint Backend Code
      working-directory: backend
      run: |
        # Uncomment this if backend uses Node + eslint
        # npm run lint

    - name: Type Check Backend
      working-directory: backend
      run: |
        # Uncomment this if backend uses TypeScript
        # npm run type-check

    - name: Run Backend Tests
      working-directory: backend
      run: |
        # Optional: include only if you have test setup
        npm test
